### ISSUE TITLE
dcct-gui not responding

### ISSUE THREAD

**Issue by thewurx** [kartojal/dcct-gui#1]
Hi,

Double clicking the dcct-gui icon and nothing happens. Tried on 2 different pc's. Both pc's running on linux mint (1 x Mint 17 and the other on Mint 18) with zenity installed.

**Comment by kartojal** [comment]
Oops. This script was done long time ago and it worked in Ubuntu 14.04,
will check the issue this weekend.

**Comment by thewurx** [comment]
No worries. Got it working through git clone. The download zip option did not seem to work.

**Comment by thewurx** [comment]
Then again, through dcct-gui I go through all the options and when asked "do you want to continue and start plotting" I click ok and the window closes and nothing happens? Hope I'm not missing anything somewhere...

**Comment by kartojal** [comment]
Downloading Mint 18, will launch a vm and try it now. 

Do you put the "dcct binaries" in the same directory as the dcct-gui script? Remember that dcct-gui file doesn't contain the miner binaries. 

Also.. dcct binaries isn't changed in 2 years (or yes? can't find newer versions). Are you sure that dcct-miner still works for Burst? I did not follow up Burst since a year, but checked their forum and now they have a newer miner for Windows/Linux/MacOs in Java. Check it: http://forums.burst-team.us:4567/topic/24/burstcoin-jminer-v0-4-2-gpu-assisted-poc-miner-all-platforms.

**Comment by kartojal** [comment]
Hey, catched the problem. Xterm (a terminal emulator) is not by default in Linux Mint. If you try to install "xterm" in your linux mint and launch again now it works as intended.
`apt-get install xterm`

Didn't know that linux mint doesn't have by default that Terminal Emulator. This script was done in a Ubuntu environment. Also, will remove the direct link, that dcct-gui is an old broken compiled version(Oops).

For improve the compatibility between Ubuntu and Linux Mint, will change the terminal emulator to **lxterm** terminal emulator (it comes by default in Linux Mint 18 xfce).

**Comment by thewurx** [comment]
Hi David,

Thanks for the help. Did try the xterm. I go through all the settings and
when I click OK to start the process the window resets back to the first
window to enter the options.

Busy doing a fresh Ubuntu install. Will try it again on it.

Could you perhaps give a bit more clarity on the settings I should enter?
If you don't mind?

I get the Burst ID. Just the other settings. I have a 2TB to get started.
What should each parameter be more or less? Also the plot files, should
they be stored onto the same drive uses for plotting or can they be in the
root folder or any other drive?

Will let you know how it goes once the Ubuntu installation is done.

Thanks in advance.

Barend.

**Comment by kartojal** [comment]
This script could be buggy if you don't have the right files or introduce the correct paremeters. Check the Readme.md in my repo and try to follow up the "How-to" for a correct installation, you need the Mirkic7 dcct files in the same directory as the "dcct-gui" script, remember that. My script it's only a simple front-end of the terminal dcct app.

What CPU are you using? You need to know if your CPU supports SSE4 or AVX2, for a faster plotting. If your CPU is new, select SSE4 and press OK.

Now the configuration values. Its a bit confusing:

## BURST ID

your numerical id! (Wallet top left, copy numeric ID)

## Start nonce

 **If is your first plot. Just write 0.** 

If not, you need to check the third field in your last plot filename, the plot info is separated by the caracter " _ ". For example, the next plot file generated by dcct:

132123123_0_8192_2048

first field: its the numerical burst ID that you inserted.
second field: it's the "start nonce" of the plot
third field: it's the "final nonce" of the plot
fourth field: it's the size of the plot in Mbs

So. For your next plot, you will need to set as "Start nonce" with the next simple formula:
`start nonce = last plot final nonce + 1`

In the before example, the next plot start nonce would be 8192 + 1 = 8193 

## Plot size in GBytes

**Set it to 2 for a fast test**.
 The size of the plot in GB. The recommendation while ago was 200 GB per plot as max, don't know the actual recommendations. 

## RAM Memory

Set up in MBytes. The amount of ram you want to use for generate the plots. **Try with 1024 MB in your first test.** If you have more, better.

## CPU Threads

**Set 2 or 1 for a fast test**
The number of cores/threads that you will use to generate the plots. If you want to use your PC while plotting (it is a very Slooooow proccess) set it as half cores/threads your cpu have. 

The more cores you assign to plotting, the fast you will finish. 

Click OK, then select a directory, click OK. And it should start to generate the plots if you put all the arguments correctly.

Happy plotting!

**FYI: You should ask for help in the burst forums at forums.burst-team.us , i'm very outdated about Burst mining and don't know if any step or programs has changed since one year. You should open a thread about Linux mining there in their forums asking for recommendations and new tips**

**Comment by thewurx** [comment]
Got a wee bit further. A new xterm window pops up and says:

Using SSE2 core.
Usage: ./plotavx2 -k KEY [ -x CORE] [-d Directory] [-s STARTNONCE] [-n NONCES]
[-m STAGGERSIZE] -[t THREADS] -a
   CORE:
         0 - default core
         1 - SSE2 core
         2 - AVX2 core
    -a = ASYNC writer mode (will use 2x memory!)

Cannot select anything in the said xterm window and nothing else happens.

So all I need to currently know is my settings below correct on the
GUI selection:

Burst ID: My Wallet address
Start Nonce: The drive that needs to be plotted?
Plot size in GB: 20000 (2TB)
Ram Memory to plot: The amount of ram I want to allocate
CPU threads: The mount of threads I need to allocate.

Thanks in advance....

**Comment by thewurx** [comment]
Hi David,

Thanks again.

Will give your instructions a go. If I struggle again I will visit the forum.

Thanks again for the assistance. Appreciated greatly!
